# Generated by Django 3.2.19 on 2023-05-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='is_finalised',
            field=models.BooleanField(default=False),
        ),
    ]
