# Generated by Django 3.2.19 on 2023-05-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20230519_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'menu categories'},
        ),
    ]
