# Generated by Django 4.2.2 on 2023-06-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="dish_images/"),
        ),
    ]
