# Generated by Django 4.2.2 on 2023-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_alter_dish_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
