# Generated by Django 3.2.19 on 2023-06-19 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20230527_1039'),
        ('menus', '0003_alter_menucategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('number_of_people', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chef')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu')),
            ],
        ),
    ]
