# Generated by Django 4.2.2 on 2023-06-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("users", "0001_initial"),
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="chef",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.chef"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customer"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menus.menu"
            ),
        ),
    ]
