# Generated by Django 4.2.2 on 2023-07-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_menu_is_deleted"),
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="menus.menu"
            ),
        ),
    ]
